Drop Table PARTICIPANT;
CREATE TABLE IF NOT EXISTS PARTICIPANT(
    PARTICIPANT_ID NUMERIC,
    NUMBER NUMERIC NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    RACING_ID NUMERIC NOT NULL,
    PRIMARY KEY ( PARTICIPANT_ID )
    );
CREATE TABLE IF NOT EXISTS RACING(
    RACING_ID NUMERIC,
    DATE VARCHAR(30) NOT NULL,
    NUMBER NUMERIC NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY ( RACING_ID )
    );

CREATE SEQUENCE IF NOT EXISTS RACING_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PARTICIPANT_SEQ START WITH 1 INCREMENT BY 1;